### ISSUE TITLE
Design a ModelAPI for gRPC View

### ISSUE THREAD

**Issue by Ed-XCF** [JoshYuJump/bali#7]
An base class include "Create"  "List"  "Retrieve"  "Update"  "Destroy"  methods. Subclasses complete business logic through declarative style like "rest_framework" did.

**Comment by Ed-XCF** [comment]
`class Test(ModelAPIView):
    model = BaseModel  # sqlalchemy model
    pb2 = ttttt_pb2
    pb2_grpc = ttttt_pb2_grpc
    request_schema = Request  # pydantic model
    response_schema = Response  # pydantic model
`
maybe seems like this

**Comment by JoshYuJump** [comment]
Maybe after 1.0 stable version

**Comment by JoshYuJump** [comment]
`Resource` is the same realization https://github.com/JoshYuJump/bali#resource
